tried to create first page
HappyJuliana/First_website_1 pull request #1
Opened 2023-08-22 11:47 UTC by HappyJuliana

![Снимок экрана 2023-08-22 144716](https://github.com/HappyJuliana/First_website_1/assets/128743829/3b68f562-d874-46f0-a0d3-f0f665662816)

2023-08-22 12:21 UTC, IvanCeban requested changes
Good job, but I have to start being more critical on my reviews as you need to start getting used to best practices.

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +<!DOCTYPE html>
the base page of the website should be index.html
Since you have just one page for now, please rename this file into index.html

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +        p {
it's time to get used with the classes. So please avoid using tags as selectors. 
Just imagine that you will add more p and h4 on your page. 

Suggestion:
create a div wrapper for your top banner (thee image on bg, nav and title usually are called "top-banner") add a specific class to the wrapper.

And use this wrapper class to specify styles for it's children

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +    <nav class="top-nav">
Good nav implementation

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +    <p>KMarketer</p>
This is normally a logo of the website and usually it is the link to homepage. You can set "#" as href

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +    <input type="button" value="Get Quote Now">
well, I mentioned that input type="button" is used inside forms. Here the buttons are just links. 
So you have 2 options:
1) Create links and style them like buttons
2) Create buttons and set the link behavior via JS. 

I suggest you choose the 1st option as an easier one and better from the SEO perspective

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +            <li><a href="default.asp">Home</a></li>
do you have default.asp and the rest of the files you're trying to reach in the nav?
If not, just place a placeholder "#" in the href

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +    <h4>We know how large objects will act, but things on a <br><br> small scale just do not act that way.</h4><br>
double br is not the best idea. You've learned "line-height" CSS property. Use it instead of adding`br` to get more space

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +        input[value="Get Quote Now"]
Use classes, not tags and attributes

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +            color:white;
don't forget to add spaces after the `:`

2023-08-22 12:21 UTC, IvanCeban commented on page.html
> +    <h1>We Take Care of <br> the Future</h1>
avoid using br. Instead use max-width

2023-08-23 14:19 UTC, HappyJuliana commented on page.html
> +    <h1>We Take Care of <br> the Future</h1>
Thanks for your informative review! It's cool to not only find out what the bug is, but also to understand how to fix it.
I tried to solve all the issues you pointed out. Hope that now the situation with the code is a little bit better :)
At least I used classes and now it looks more "professional"

![Снимок экрана 2023-08-23 171659](https://github.com/HappyJuliana/First_website_1/assets/128743829/27a71261-291c-4b2b-ac44-466ccf9e5b00)

2023-08-23 14:22 UTC, IvanCeban approved these changes
Great class namings!

2023-08-25 13:54 UTC, closed without merging